version: '3'
services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:3-alpine
    ports: ["6379:6379"]
    volumes:
      - redisdata:/data

#  centrifugo:
#    image: registry.handmade.ru/handmade/centrifugo:latest
#    command: centrifugo --web  --insecure_admin --insecure --insecure_api
#    ulimits:
#      nofile:
#        soft: 65536
#        hard: 65536
#    ports: ["8000:8000"]

volumes:
  dbdata: {}
  redisdata: {}
