cs_hostname: "lvh.me"
cs_secrets_base: "development"

cs_database_host: "localhost"
cs_database_port: "5432"
cs_database_user: "dev"
cs_database_password: "dev"
cs_database_name: "handmade_dev"

cs_redis_host: "localhost"
cs_redis_port: "6379"
cs_redis_database: "2"
