db:
  host:               <%= Figaro.env.hm_database_host! %>
  port:               <%= Figaro.env.hm_database_port! %>
  user:               <%= Figaro.env.hm_database_user! %>
  password:           <%= Figaro.env.hm_database_password! %>
  name:               <%= Figaro.env.hm_database_name! %>
  connection_pool:    <%= Figaro.env.hm_database_connection_pool || Figaro.env.rails_max_threads || 10 %>
  connection_timeout: <%= Figaro.env.hm_database_connection_timeout || 5 %>

redis:
  host:     <%= Figaro.env.hm_redis_host! %>
  port:     <%= Figaro.env.hm_redis_port! %>
  database: <%= Figaro.env.hm_redis_database! %>
